	<script type="text/javascript" src="/resources/js/jsrender.js"></script>
	<script type="text/javascript" src="/resources/js/jquery.MultiFile.js"></script>
	<script type="text/javascript" src="/resources/js/bootstrap/bootstrap.min.js"></script>
	<script type="text/javascript" src="/resources/js/datatables/datatables.min.js"></script>
	<script type="text/javascript" src="/resources/js/datepicker/datepicker.js"></script>
	<script type="text/javascript" src="/resources/js/datepicker/datepicker.ko.js"></script>
	<script type="text/javascript" src="/resources/js/validate/jquery.validate.min.js"></script>
	<script type="text/javascript" src="/resources/js/validate/jquery.validate.ko.min.js"></script>
	<script type="text/javascript" src="/resources/js/validate/additional-methods.min.js"></script>
	<script type="text/javascript" src="/resources/js/jsrender.js"></script>
	<script type="text/javascript" src="/resources/js/common.js"></script>
	<script type="text/javascript" src="/resources/js/common-date.js"></script>
